# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "bluebird-3.7.2" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.7.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.7.2.tgz";
        sha512 = "XpNj6GDQzdfW+r2Wnn7xiSAd7TM3jzkxGXBGTtWKuSXv1xUV+azxAm8jdWZN06QTQk+2N2XB9jRDkvbmQmcRtg==";
      };
    };
  };
in
{
  serverless-scriptable-plugin = nodeEnv.buildNodePackage {
    name = "serverless-scriptable-plugin";
    packageName = "serverless-scriptable-plugin";
    version = "1.2.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/serverless-scriptable-plugin/-/serverless-scriptable-plugin-1.2.2.tgz";
      sha512 = "vIXasDZJBTMPxCgi4v+vwmysL6EMLgUBHcKIpu5YtpS1HkRIFloTxLXh9g2f/+6EemqBthrLUYnhB3EsTO1h9g==";
    };
    dependencies = [
      sources."bluebird-3.7.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Add scripts(nodejs) support to serverless 1.x";
      homepage = "https://github.com/weixu365/serverless-scriptable-plugin#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
